name: many_pins
description: A tool for tinkering with a microcontroller board's GPIO pins via serial.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Used to manage the app icon
  flutter_launcher_icons: ^0.10.0
  # A Flutter wrapper for the libserial library
  flutter_libserialport: ^0.2.3
  # Stores settings that persist between sessions
  shared_preferences: ^2.0.15
  # A wrapper around InheritedWidget
  provider: ^6.0.3
  # Provides custom fonts
  google_fonts: ^3.0.1
  # Used to launch URLs and other links
  url_launcher: ^6.1.5
  url_launcher_windows: ^2.0.2
  # Used to access common system locations
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  windows:
    generate: true
    image_path: 'assets/icon/ic_launcher.png'
    icon_size: 256 # min:48, max:256, default: 48